Don't crash if RTMP value is not passed
aau-zid/BigBlueButton-liveStreaming pull request #136
Opened 2021-06-24 17:46 UTC by Mte90

Because we use it also just for recording and not only streaming.
Right now we pass something like https://fakeurl as workaround but is not so good to get printed this in the BBB chat.

2021-06-24 21:08 UTC, mtsonline requested changes
If you set 
BBB_CHAT_MESSAGE = false
it also would not be schown.
Could you please make it consistent so the message to be send if only recording is active, can be customiced?
and please only send it, if "download" really is set to something, as otherwise nothing is stored.

2021-06-28 11:03 UTC, Mte90 commented
I didn't know that parameter.

About your feedback how I can check if the recording is active in that function?

2022-02-07 12:34 UTC, mtsonline approved these changes

2022-02-07 12:35 UTC, merged

2022-02-07 12:35 UTC, mtsonline commented
Thanks for this improovement. cheers